name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    name: CI
    steps:
      - uses: actions/checkout@v7
        name: Check out repo

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 12

      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Test package
        run: pnpm test
