name: release on marketplace

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checkout, install, build and publish
    steps:
      - uses: actions/checkout@v7
        name: Check out repo
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 12

      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm package

      - name: Publish package on official marketplace
        run: pnpm vsce publish
        env:
          VSCE_PAT: ${{ secrets.AZURE_PUBLISHER_PAT }}

      - name: Publish package on open-vsx
        run: pnpx ovsx publish
        env:
          OVSX_PAT: ${{ secrets.OPENVSX_TOKEN }}
