name: release on marketplace

on: 
  push:
    tags:
      - '*'
    tags-ignore:
      - 'qa'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checkout, install, build and publish
    steps:
      - uses: actions/checkout@v4
        name: Check out repo

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm package

      - name: Publish package
        uses: sigma/vsce-publish-action@v0.0.2
        with:
          vsce_token: ${{ secrets.AZURE_PUBLISHER_PAT }}
