name: release on marketplace

on: 
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checkout, install, build and publish
    steps:
      - uses: actions/checkout@v4
        name: Check out repo

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm package

  publish_on_marketplace:
    concurrency:
      group: publish
      cancel-in-progress: false
    steps:
      - name: Publish package on official marketplace
        run: pnpm vsce publish
        env:
          VSCE_PAT: ${{ secrets.AZURE_PUBLISHER_PAT }}

  publish_on_openvsx:
    concurrency:
      group: publish
      cancel-in-progress: false
    steps:
      - name: Publish package on open-vsx
        run: pnpx ovsx publish
        env:
          OVSX_PAT: ${{ secrets.OPENVSX_TOKEN }}
